apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:
  - name: data
    csi:
      driver: image.csi.k8s.io
      volumeAttributes:
        # Specify your image here. busybox used just as a placeholder, not
        # because its a good idea. See the container folder for a better
        # example.
        image: busybox
        # changeDir: /bin
